"""add_gin_indexes_for_jsonb

Revision ID: ae2f49d9f074
Revises: 8fc3d6eb8ae8
Create Date: 2026-01-02 00:46:34.612662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2f49d9f074'
down_revision: Union[str, Sequence[str], None] = '8fc3d6eb8ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_characters_stats_gin', 'characters', ['stats'], unique=False, postgresql_using='gin')
    op.create_index('ix_characters_status_gin', 'characters', ['current_status'], unique=False, postgresql_using='gin')
    op.create_index('ix_rulebook_stat_block_gin', 'rulebook_chunks', ['stat_block'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rulebook_stat_block_gin', table_name='rulebook_chunks', postgresql_using='gin')
    op.drop_index('ix_characters_status_gin', table_name='characters', postgresql_using='gin')
    op.drop_index('ix_characters_stats_gin', table_name='characters', postgresql_using='gin')
    # ### end Alembic commands ###
